### ISSUE TITLE
A problem about TSEB_point_time_series_main.py

### ISSUE THREAD

**Issue by huiyiyuxin** [hectornieto/pyTSEB#32] opened 2019-08-08 06:34 UTC
When I run the two tests of TSEB, the TSEB_local_image_main.py can run , although it show a error 4:
![image](https://user-images.githubusercontent.com/28803563/62680207-46ed8300-b9e9-11e9-8ca2-df866e2ebef2.png)
But when I run the  Tseb_point_time_series_main.py, It's not finished, and give me some error.
![image](https://user-images.githubusercontent.com/28803563/62680278-6edce680-b9e9-11e9-87c3-91c4e305f815.png)

**Comment by mariapina83** [comment] 2020-04-29 13:23
Hi, I have got the same errors. Any news about that?
Thanks,
Mariapina

**Comment by hectornieto** [comment] 2020-04-29 13:59
Latest commit (https://github.com/hectornieto/pyTSEB/commit/170f093d573071c6969abab860d8292573a6306d) should have fixed this error:

**Comment by mariapina83** [comment] 2020-04-29 14:24
Hi Hector! Hope you are doing well! 
Thanks for the answer. The error about the different length of index and data is fixed now, but I am still getting the error about missing file when running TSEB_local_image_main.py.

**Comment by hectornieto** [comment] 2020-04-29 17:14
I guess the error message you received is caused by GDAL library... do not need to worry in case the model goes on... it is probably missing an optional  paramameter which will be estimated instead. I have included additional warning messages in case this happens to clarify this issue

**Closed** 2020-05-06 07:27 UTC
